
package analizadoreslexico;

import java.util.ArrayList;

/**
 *
 * @author jesus
 */
public class AnalizadorLex extends javax.swing.JFrame {

    /**
     * Creates new form AnalizadorLex
     */
    public AnalizadorLex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEntrada = new javax.swing.JTextField();
        BtAnalizar = new javax.swing.JButton();
        TxtResultados = new java.awt.TextArea();
        TxtCoincidencias = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        BtAnalizar.setBackground(new java.awt.Color(0, 204, 204));
        BtAnalizar.setText("Analizar");
        BtAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAnalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(TxtResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(TxtCoincidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(BtAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(BtAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(TxtCoincidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAnalizarActionPerformed
        // TODO add your handling code here:
//         
//        String expresion = txtEntrada.getText();
//        
//        int Numeros = 0, Operadores = 0, Constantes = 0, Variables = 0, Desconocidos = 0;
//        
//          ArrayList<Token> tokens = Pruebas2.lex(expresion);
//          
//           for (Token token : tokens) {
//           TxtResultados.append("Tipo: " + token.getTipo() + " Valor: " + token.getValorString()+"\n");
//          
//           
//        
//        Pruebas2 prueba = new Pruebas2();
//        Token enumerador = new Token();      
//        }
//    

String expresion = txtEntrada.getText();
        
        Pruebas prueba = new Pruebas();
        Token enumerador = new Token();
        
        int Numeros = 0, Operadores = 0, Constantes = 0, Variables = 0, Desconocidos = 0;
        
        ArrayList<Token> tokens = Pruebas2.lex(expresion);

        for (Token token : tokens) {
            
            TxtResultados.append("Tipo: " + token.getTipo() + " Valor: " + token.getValorString()+"\n");
            
             if (token.getTipo() == enumerador.tipo.NUMERO) {
                Numeros++;
                
            }else if (token.getTipo() == enumerador.tipo.OPERADOR) {
                Operadores++;
                
            }else if (token.getTipo() == enumerador.tipo.CONSTANTE) {
                Constantes++;
                
            }else if (token.getTipo() == enumerador.tipo.VARIABLE) {
                Variables++;
                
            }else if (token.getTipo() == enumerador.tipo.DESCONOCIDO) {
                Desconocidos++;
            }
        
    
        TxtCoincidencias.append(" \n" 
                + Numeros + " NUMEROS\n" 
                + Operadores +" OPERADORES\n"
                + Constantes + " CONSTANTE\n" 
                + Variables +" VARIABLES\n"
                + Desconocidos +" DESCONOCIDOS\n");
        
        
    
        }
    
    }//GEN-LAST:event_BtAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizadorLex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizadorLex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizadorLex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizadorLex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizadorLex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAnalizar;
    private java.awt.TextArea TxtCoincidencias;
    private java.awt.TextArea TxtResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables
}
